rvm:
- 2.0.0
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - secure: KTQ83GtNJyXwTUzYKbDtX1FzA3hsBSHefOqYsZ2KzOnj1dPZpGoeb4gcjWHXvNHqmR0mToT8U7KNq8AYWwHQLYCKf2+jRayd9UAzezhcs5u0SVfE5gmZLho57TW3AQvHI/uVQi9yg9/N3uDICqBplHJ7EMeMusUBc6ACF8FRmtY=
